import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

# 1. Initialize Firebase Admin SDK
cert_path = "./service-key.json"
cred = credentials.Certificate(cert_path)
firebase_admin.initialize_app(cred)

# 2. Open client connection to Cloud Firestore
db = firestore.client()

# 3. Complete dataset mapping all 88 devices with exact specifications
device_catalog = {
    # --- SAMSUNG ---
    "dream2lte": {
        "brand": "Samsung",
        "marketing_name": "Galaxy S8+",
        "codename": "dream2lte",
        "release_year": 2017,
        "cpu_soc": "Exynos 8895",
        "gpu": "Mali-G71 MP20",
        "ram": "4GB / 6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.2 inch Super AMOLED (1440x2960)",
        "battery": "3500 mAh",
        "camera": "12 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {
            "Havoc-OS v6.0": {
                "version": "13.0",
                "download_url": "https://github.com",
                "gapps_included": True,
                "twrp_commands": [
                    "wipe system",
                    "wipe cache",
                    "wipe dalvik",
                    "install /sdcard/Havoc-OS-v6.0-dream2lte.zip",
                    "reboot"
                ]
            }
        }
    },
    "dreamlte": {
        "brand": "Samsung",
        "marketing_name": "Galaxy S8",
        "codename": "dreamlte",
        "release_year": 2017,
        "cpu_soc": "Exynos 8895",
        "gpu": "Mali-G71 MP20",
        "ram": "4GB LPDDR4X",
        "storage": "64GB UFS 2.1",
        "display": "5.8 inch Super AMOLED (1440x2960)",
        "battery": "3000 mAh",
        "camera": "12 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "greatlte": {
        "brand": "Samsung",
        "marketing_name": "Galaxy Note 8",
        "codename": "greatlte",
        "release_year": 2017,
        "cpu_soc": "Exynos 8895",
        "gpu": "Mali-G71 MP20",
        "ram": "6GB LPDDR4X",
        "storage": "64GB / 128GB / 256GB UFS 2.1",
        "display": "6.3 inch Super AMOLED (1440x2960)",
        "battery": "3300 mAh",
        "camera": "12 MP + 12 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "starlte": {
        "brand": "Samsung",
        "marketing_name": "Galaxy S9",
        "codename": "starlte",
        "release_year": 2018,
        "cpu_soc": "Exynos 9810",
        "gpu": "Mali-G72 MP18",
        "ram": "4GB LPDDR4X",
        "storage": "64GB / 128GB / 256GB UFS 2.1",
        "display": "5.8 inch Super AMOLED (1440x2960)",
        "battery": "3000 mAh",
        "camera": "12 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "star2lte": {
        "brand": "Samsung",
        "marketing_name": "Galaxy S9+",
        "codename": "star2lte",
        "release_year": 2018,
        "cpu_soc": "Exynos 9810",
        "gpu": "Mali-G72 MP18",
        "ram": "6GB LPDDR4X",
        "storage": "64GB / 128GB / 256GB UFS 2.1",
        "display": "6.2 inch Super AMOLED (1440x2960)",
        "battery": "3500 mAh",
        "camera": "12 MP + 12 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "crownlte": {
        "brand": "Samsung",
        "marketing_name": "Galaxy Note 9",
        "codename": "crownlte",
        "release_year": 2018,
        "cpu_soc": "Exynos 9810",
        "gpu": "Mali-G72 MP18",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "128GB / 512GB UFS 2.1",
        "display": "6.4 inch Super AMOLED (1440x2960)",
        "battery": "4000 mAh",
        "camera": "12 MP + 12 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "beyond0lte": {
        "brand": "Samsung",
        "marketing_name": "Galaxy S10e",
        "codename": "beyond0lte",
        "release_year": 2019,
        "cpu_soc": "Exynos 9820",
        "gpu": "Mali-G76 MP12",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "128GB / 256GB UFS 2.1",
        "display": "5.8 inch Dynamic AMOLED (1080x2280)",
        "battery": "3100 mAh",
        "camera": "12 MP + 16 MP (Rear) / 10 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "beyond1": {
        "brand": "Samsung",
        "marketing_name": "Galaxy S10",
        "codename": "beyond1",
        "release_year": 2019,
        "cpu_soc": "Exynos 9820",
        "gpu": "Mali-G76 MP12",
        "ram": "8GB LPDDR4X",
        "storage": "128GB / 512GB UFS 2.1",
        "display": "6.1 inch Dynamic AMOLED (1440x3040)",
        "battery": "3400 mAh",
        "camera": "12 MP + 12 MP + 16 MP (Rear) / 10 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "beyond2": {
        "brand": "Samsung",
        "marketing_name": "Galaxy S10+",
        "codename": "beyond2",
        "release_year": 2019,
        "cpu_soc": "Exynos 9820",
        "gpu": "Mali-G76 MP12",
        "ram": "8GB / 12GB LPDDR4X",
        "storage": "128GB / 512GB / 1TB UFS 2.1",
        "display": "6.4 inch Dynamic AMOLED (1440x3040)",
        "battery": "4100 mAh",
        "camera": "12 MP + 12 MP + 16 MP (Rear) / 10 MP + 8 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "d1": {
        "brand": "Samsung",
        "marketing_name": "Galaxy Note 10",
        "codename": "d1",
        "release_year": 2019,
        "cpu_soc": "Exynos 9825",
        "gpu": "Mali-G76 MP12",
        "ram": "8GB LPDDR4X",
        "storage": "256GB UFS 3.0",
        "display": "6.3 inch Dynamic AMOLED (1080x2280)",
        "battery": "3500 mAh",
        "camera": "12 MP + 12 MP + 16 MP (Rear) / 10 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "d2s": {
        "brand": "Samsung",
        "marketing_name": "Galaxy Note 10+",
        "codename": "d2s",
        "release_year": 2019,
        "cpu_soc": "Exynos 9825",
        "gpu": "Mali-G76 MP12",
        "ram": "12GB LPDDR4X",
        "storage": "256GB / 512GB UFS 3.0",
        "display": "6.8 inch Dynamic AMOLED (1440x3040)",
        "battery": "4300 mAh",
        "camera": "12 MP + 12 MP + 16 MP + 0.3 MP (Rear) / 10 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "a50": {
        "brand": "Samsung",
        "marketing_name": "Galaxy A50",
        "codename": "a50",
        "release_year": 2019,
        "cpu_soc": "Exynos 9610",
        "gpu": "Mali-G72 MP3",
        "ram": "4GB / 6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.4 inch Super AMOLED (1080x2340)",
        "battery": "4000 mAh",
        "camera": "25 MP + 8 MP + 5 MP (Rear) / 25 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "a51": {
        "brand": "Samsung",
        "marketing_name": "Galaxy A51",
        "codename": "a51",
        "release_year": 2019,
        "cpu_soc": "Exynos 9611",
        "gpu": "Mali-G72 MP3",
        "ram": "4GB / 6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.5 inch Super AMOLED (1080x2400)",
        "battery": "4000 mAh",
        "camera": "48 MP + 12 MP + 5 MP + 5 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "a52q": {
        "brand": "Samsung",
        "marketing_name": "Galaxy A52 4G",
        "codename": "a52q",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 720G",
        "gpu": "Adreno 618",
        "ram": "4GB / 6GB / 8GB LPDDR4X",
        "storage": "128GB / 256GB UFS 2.1",
        "display": "6.5 inch Super AMOLED 90Hz (1080x2400)",
        "battery": "4500 mAh",
        "camera": "64 MP + 12 MP + 5 MP + 5 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "a52sxq": {
        "brand": "Samsung",
        "marketing_name": "Galaxy A52s 5G",
        "codename": "a52sxq",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 778G 5G",
        "gpu": "Adreno 642L",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "128GB / 256GB UFS 2.2",
        "display": "6.5 inch Super AMOLED 120Hz (1080x2400)",
        "battery": "4500 mAh",
        "camera": "64 MP + 12 MP + 5 MP + 5 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "a71": {
        "brand": "Samsung",
        "marketing_name": "Galaxy A71 4G",
        "codename": "a71",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 730",
        "gpu": "Adreno 618",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "128GB UFS 2.1",
        "display": "6.7 inch Super AMOLED Plus (1080x2400)",
        "battery": "4500 mAh",
        "camera": "64 MP + 12 MP + 5 MP + 5 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "r2q": {
        "brand": "Samsung",
        "marketing_name": "Galaxy S20 FE 4G (Snapdragon)",
        "codename": "r2q",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 865",
        "gpu": "Adreno 650",
        "ram": "6GB / 8GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.5 inch Super AMOLED 120Hz (1080x2400)",
        "battery": "4500 mAh",
        "camera": "12 MP + 8 MP + 12 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },

    # --- XIAOMI / REDMI / POCO ---
    "spes": {
        "brand": "Xiaomi",
        "marketing_name": "Redmi Note 11",
        "codename": "spes",
        "release_year": 2022,
        "cpu_soc": "Qualcomm Snapdragon 680 4G",
        "gpu": "Adreno 610",
        "ram": "4GB / 6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.2",
        "display": "6.43 inch AMOLED 90Hz (1080x2400)",
        "battery": "5000 mAh",
        "camera": "50 MP + 8 MP + 2 MP + 2 MP (Rear) / 13 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "vince": {
        "brand": "Xiaomi",
        "marketing_name": "Redmi 5 Plus",
        "codename": "vince",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 625",
        "gpu": "Adreno 506",
        "ram": "3GB / 4GB LPDDR3",
        "storage": "32GB / 64GB eMMC 5.1",
        "display": "5.99 inch IPS LCD (1080x2160)",
        "battery": "4000 mAh",
        "camera": "12 MP (Rear) / 5 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "mido": {
        "brand": "Xiaomi",
        "marketing_name": "Redmi Note 4X",
        "codename": "mido",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 625",
        "gpu": "Adreno 506",
        "ram": "3GB / 4GB LPDDR3",
        "storage": "32GB / 64GB eMMC 5.1",
        "display": "5.5 inch IPS LCD (1080x1920)",
        "battery": "4100 mAh",
        "camera": "13 MP (Rear) / 5 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "whyred": {
        "brand": "Xiaomi",
        "marketing_name": "Redmi Note 5 Pro",
        "codename": "whyred",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 636",
        "gpu": "Adreno 509",
        "ram": "4GB / 6GB LPDDR4X",
        "storage": "32GB / 64GB eMMC 5.1",
        "display": "5.99 inch IPS LCD (1080x2160)",
        "battery": "4000 mAh",
        "camera": "12 MP + 5 MP (Rear) / 20 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "ginkgo": {
        "brand": "Xiaomi",
        "marketing_name": "Redmi Note 8",
        "codename": "ginkgo",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 665",
        "gpu": "Adreno 610",
        "ram": "3GB / 4GB / 6GB LPDDR4X",
        "storage": "32GB / 64GB / 128GB eMMC 5.1",
        "display": "6.3 inch IPS LCD (1080x2340)",
        "battery": "4000 mAh",
        "camera": "48 MP + 8 MP + 2 MP + 2 MP (Rear) / 13 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "curtana": {
        "brand": "Xiaomi",
        "marketing_name": "Redmi Note 9S",
        "codename": "curtana",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 720G",
        "gpu": "Adreno 618",
        "ram": "4GB / 6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.67 inch IPS LCD (1080x2400)",
        "battery": "5020 mAh",
        "camera": "48 MP + 8 MP + 5 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "sweet": {
        "brand": "Xiaomi",
        "marketing_name": "Redmi Note 10 Pro",
        "codename": "sweet",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 732G",
        "gpu": "Adreno 618",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.2",
        "display": "6.67 inch AMOLED 120Hz (1080x2400)",
        "battery": "5020 mAh",
        "camera": "108 MP + 8 MP + 5 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "beryllium": {
        "brand": "Poco",
        "marketing_name": "POCO F1",
        "codename": "beryllium",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB / 256GB UFS 2.1",
        "display": "6.18 inch IPS LCD (1080x2246)",
        "battery": "4000 mAh",
        "camera": "12 MP + 5 MP (Rear) / 20 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "vayu": {
        "brand": "Poco",
        "marketing_name": "POCO X3 Pro",
        "codename": "vayu",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 860",
        "gpu": "Adreno 640",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.67 inch IPS LCD 120Hz (1080x2400)",
        "battery": "5160 mAh",
        "camera": "48 MP + 8 MP + 2 MP + 2 MP (Rear) / 20 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "surya": {
        "brand": "Poco",
        "marketing_name": "POCO X3 NFC",
        "codename": "surya",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 732G",
        "gpu": "Adreno 618",
        "ram": "6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.67 inch IPS LCD 120Hz (1080x2400)",
        "battery": "5160 mAh",
        "camera": "64 MP + 13 MP + 2 MP + 2 MP (Rear) / 20 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "alioth": {
        "brand": "Poco",
        "marketing_name": "POCO F3",
        "codename": "alioth",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 870 5G",
        "gpu": "Adreno 650",
        "ram": "6GB / 8GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.67 inch AMOLED 120Hz (1080x2400)",
        "battery": "4520 mAh",
        "camera": "48 MP + 8 MP + 5 MP (Rear) / 20 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "munch": {
        "brand": "Poco",
        "marketing_name": "POCO F4",
        "codename": "munch",
        "release_year": 2022,
        "cpu_soc": "Qualcomm Snapdragon 870 5G",
        "gpu": "Adreno 650",
        "ram": "6GB / 8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.67 inch AMOLED 120Hz (1080x2400)",
        "battery": "4500 mAh",
        "camera": "64 MP + 8 MP + 2 MP (Rear) / 20 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "marble": {
        "brand": "Poco",
        "marketing_name": "POCO F5",
        "codename": "marble",
        "release_year": 2023,
        "cpu_soc": "Qualcomm Snapdragon 7+ Gen 2",
        "gpu": "Adreno 725",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "256GB UFS 3.1",
        "display": "6.67 inch AMOLED 120Hz (1080x2400)",
        "battery": "5000 mAh",
        "camera": "64 MP + 8 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "duchamp": {
        "brand": "Poco",
        "marketing_name": "POCO X6 Pro",
        "codename": "duchamp",
        "release_year": 2024,
        "cpu_soc": "MediaTek Dimensity 8300 Ultra",
        "gpu": "Mali-G610 MC6",
        "ram": "8GB / 12GB LPDDR5X",
        "storage": "256GB / 512GB UFS 4.0",
        "display": "6.67 inch AMOLED 120Hz (1220x2712)",
        "battery": "5000 mAh",
        "camera": "64 MP + 8 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "chopin": {
        "brand": "Poco",
        "marketing_name": "POCO X3 GT",
        "codename": "chopin",
        "release_year": 2021,
        "cpu_soc": "MediaTek Dimensity 1100",
        "gpu": "Mali-G77 MC9",
        "ram": "8GB LPDDR4X",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.6 inch IPS LCD 120Hz (1080x2400)",
        "battery": "5000 mAh",
        "camera": "64 MP + 8 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "cepheus": {
        "brand": "Xiaomi",
        "marketing_name": "Mi 9",
        "codename": "cepheus",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855",
        "gpu": "Adreno 640",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB / 256GB UFS 2.1",
        "display": "6.39 inch Super AMOLED (1080x2340)",
        "battery": "3300 mAh",
        "camera": "48 MP + 12 MP + 16 MP (Rear) / 20 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "umi": {
        "brand": "Xiaomi",
        "marketing_name": "Mi 10",
        "codename": "umi",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 865",
        "gpu": "Adreno 650",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.0",
        "display": "6.67 inch Super AMOLED 90Hz (1080x2340)",
        "battery": "4780 mAh",
        "camera": "108 MP + 13 MP + 2 MP + 2 MP (Rear) / 20 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "venus": {
        "brand": "Xiaomi",
        "marketing_name": "Mi 11",
        "codename": "venus",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 888",
        "gpu": "Adreno 660",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.81 inch AMOLED 120Hz (1440x3200)",
        "battery": "4600 mAh",
        "camera": "108 MP + 13 MP + 5 MP (Rear) / 20 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "cupid": {
        "brand": "Xiaomi",
        "marketing_name": "Xiaomi 12",
        "codename": "cupid",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 8 Gen 1",
        "gpu": "Adreno 730",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.28 inch AMOLED 120Hz (1080x2400)",
        "battery": "4500 mAh",
        "camera": "50 MP + 13 MP + 5 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },

    # --- MOTOROLA ---
    "fogos": {
        "brand": "Motorola",
        "marketing_name": "Moto G34 5G",
        "codename": "fogos",
        "release_year": 2024,
        "cpu_soc": "Qualcomm Snapdragon 695 5G",
        "gpu": "Adreno 619",
        "ram": "4GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB / 256GB UFS 2.2",
        "display": "6.5 inch IPS LCD 120Hz (720x1600)",
        "battery": "5000 mAh",
        "camera": "50 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "vigo": {
        "brand": "Motorola",
        "marketing_name": "Moto G45 5G",
        "codename": "vigo",
        "release_year": 2024,
        "cpu_soc": "Qualcomm Snapdragon 6s Gen 3",
        "gpu": "Adreno 619",
        "ram": "4GB / 8GB LPDDR4X",
        "storage": "128GB UFS 2.2",
        "display": "6.5 inch IPS LCD 120Hz (720x1600)",
        "battery": "5000 mAh",
        "camera": "50 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "rhode": {
        "brand": "Motorola",
        "marketing_name": "Moto G52",
        "codename": "rhode",
        "release_year": 2022,
        "cpu_soc": "Qualcomm Snapdragon 680 4G",
        "gpu": "Adreno 610",
        "ram": "4GB / 6GB LPDDR4X",
        "storage": "128GB / 256GB UFS 2.2",
        "display": "6.6 inch AMOLED 90Hz (1080x2400)",
        "battery": "5000 mAh",
        "camera": "50 MP + 8 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "rhobe": {
        "brand": "Motorola",
        "marketing_name": "Moto G82 5G",
        "codename": "rhobe",
        "release_year": 2022,
        "cpu_soc": "Qualcomm Snapdragon 695 5G",
        "gpu": "Adreno 619",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "128GB UFS 2.2",
        "display": "6.6 inch AMOLED 120Hz (1080x2400)",
        "battery": "5000 mAh",
        "camera": "50 MP + 8 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "payton": {
        "brand": "Motorola",
        "marketing_name": "Moto X4",
        "codename": "payton",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 630",
        "gpu": "Adreno 508",
        "ram": "3GB / 4GB / 6GB LPDDR4",
        "storage": "32GB / 64GB eMMC 5.1",
        "display": "5.2 inch LTPS IPS LCD (1080x1920)",
        "battery": "3000 mAh",
        "camera": "12 MP + 8 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "river": {
        "brand": "Motorola",
        "marketing_name": "Moto G7",
        "codename": "river",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 632",
        "gpu": "Adreno 506",
        "ram": "4GB LPDDR3",
        "storage": "64GB eMMC 5.1",
        "display": "6.2 inch LTPS IPS LCD (1080x2270)",
        "battery": "3000 mAh",
        "camera": "12 MP + 5 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "lake": {
        "brand": "Motorola",
        "marketing_name": "Moto G7 Plus",
        "codename": "lake",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 636",
        "gpu": "Adreno 509",
        "ram": "4GB LPDDR4X",
        "storage": "64GB eMMC 5.1",
        "display": "6.2 inch LTPS IPS LCD (1080x2270)",
        "battery": "3000 mAh",
        "camera": "16 MP + 5 MP (Rear) / 12 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "rav": {
        "brand": "Motorola",
        "marketing_name": "Moto G8",
        "codename": "rav",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 665",
        "gpu": "Adreno 610",
        "ram": "4GB LPDDR4X",
        "storage": "64GB eMMC 5.1",
        "display": "6.4 inch IPS LCD (720x1560)",
        "battery": "4000 mAh",
        "camera": "16 MP + 8 MP + 2 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "sofia": {
        "brand": "Motorola",
        "marketing_name": "Moto G Power (2020)",
        "codename": "sofia",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 665",
        "gpu": "Adreno 610",
        "ram": "4GB LPDDR4X",
        "storage": "64GB eMMC 5.1",
        "display": "6.4 inch IPS LCD (1080x2300)",
        "battery": "5000 mAh",
        "camera": "16 MP + 8 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "nairo": {
        "brand": "Motorola",
        "marketing_name": "Moto G 5G Plus",
        "codename": "nairo",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 765G 5G",
        "gpu": "Adreno 620",
        "ram": "4GB / 6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.7 inch LTPS IPS LCD 90Hz (1080x2520)",
        "battery": "5000 mAh",
        "camera": "48 MP + 8 MP + 5 MP + 2 MP (Rear) / 16 MP + 8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "miami": {
        "brand": "Motorola",
        "marketing_name": "Edge 30 Neo",
        "codename": "miami",
        "release_year": 2022,
        "cpu_soc": "Qualcomm Snapdragon 695 5G",
        "gpu": "Adreno 619",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "128GB / 256GB UFS 2.2",
        "display": "6.28 inch P-OLED 120Hz (1080x2400)",
        "battery": "4020 mAh",
        "camera": "64 MP + 13 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "rtwo": {
        "brand": "Motorola",
        "marketing_name": "Edge 40 Pro",
        "codename": "rtwo",
        "release_year": 2023,
        "cpu_soc": "Qualcomm Snapdragon 8 Gen 2",
        "gpu": "Adreno 740",
        "ram": "12GB LPDDR5X",
        "storage": "256GB / 512GB UFS 4.0",
        "display": "6.67 inch OLED 165Hz (1080x2400)",
        "battery": "4600 mAh",
        "camera": "50 MP + 50 MP + 12 MP (Rear) / 60 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },

    # --- NOTHING ---
    "spacewar": {
        "brand": "Nothing",
        "marketing_name": "Phone (1)",
        "codename": "spacewar",
        "release_year": 2022,
        "cpu_soc": "Qualcomm Snapdragon 778G+ 5G",
        "gpu": "Adreno 642L",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.55 inch OLED 120Hz (1080x2400)",
        "battery": "4500 mAh",
        "camera": "50 MP + 50 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "pong": {
        "brand": "Nothing",
        "marketing_name": "Phone (2)",
        "codename": "pong",
        "release_year": 2023,
        "cpu_soc": "Qualcomm Snapdragon 8+ Gen 1",
        "gpu": "Adreno 730",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB / 512GB UFS 3.1",
        "display": "6.7 inch LTPO OLED 120Hz (1080x2412)",
        "battery": "4700 mAh",
        "camera": "50 MP + 50 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "pacman": {
        "brand": "Nothing",
        "marketing_name": "Phone (2a)",
        "codename": "pacman",
        "release_year": 2024,
        "cpu_soc": "MediaTek Dimensity 7200 Pro",
        "gpu": "Mali-G610 MC4",
        "ram": "8GB / 12GB LPDDR4X",
        "storage": "128GB / 256GB UFS 2.2",
        "display": "6.7 inch AMOLED 120Hz (1080x2412)",
        "battery": "5000 mAh",
        "camera": "50 MP + 50 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },

    # --- GOOGLE PIXEL ---
    "sailfish": {
        "brand": "Google",
        "marketing_name": "Pixel",
        "codename": "sailfish",
        "release_year": 2016,
        "cpu_soc": "Qualcomm Snapdragon 821",
        "gpu": "Adreno 530",
        "ram": "4GB LPDDR4",
        "storage": "32GB / 128GB UFS 2.0",
        "display": "5.0 inch AMOLED (1080x1920)",
        "battery": "2770 mAh",
        "camera": "12.3 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "marlin": {
        "brand": "Google",
        "marketing_name": "Pixel XL",
        "codename": "marlin",
        "release_year": 2016,
        "cpu_soc": "Qualcomm Snapdragon 821",
        "gpu": "Adreno 530",
        "ram": "4GB LPDDR4",
        "storage": "32GB / 128GB UFS 2.0",
        "display": "5.5 inch AMOLED (1440x2560)",
        "battery": "3450 mAh",
        "camera": "12.3 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "walleye": {
        "brand": "Google",
        "marketing_name": "Pixel 2",
        "codename": "walleye",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 835",
        "gpu": "Adreno 540",
        "ram": "4GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "5.0 inch AMOLED (1080x1920)",
        "battery": "2700 mAh",
        "camera": "12.2 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "taimen": {
        "brand": "Google",
        "marketing_name": "Pixel 2 XL",
        "codename": "taimen",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 835",
        "gpu": "Adreno 540",
        "ram": "4GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.0 inch P-OLED (1440x2880)",
        "battery": "3520 mAh",
        "camera": "12.2 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "blueline": {
        "brand": "Google",
        "marketing_name": "Pixel 3",
        "codename": "blueline",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "4GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "5.5 inch P-OLED (1080x2160)",
        "battery": "2915 mAh",
        "camera": "12.2 MP (Rear) / 8 MP + 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "crosshatch": {
        "brand": "Google",
        "marketing_name": "Pixel 3 XL",
        "codename": "crosshatch",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "4GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.3 inch P-OLED (1440x2960)",
        "battery": "3430 mAh",
        "camera": "12.2 MP (Rear) / 8 MP + 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "sargo": {
        "brand": "Google",
        "marketing_name": "Pixel 3a",
        "codename": "sargo",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 670",
        "gpu": "Adreno 615",
        "ram": "4GB LPDDR4X",
        "storage": "64GB eMMC 5.1",
        "display": "5.6 inch OLED (1080x2220)",
        "battery": "3000 mAh",
        "camera": "12.2 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "bonito": {
        "brand": "Google",
        "marketing_name": "Pixel 3a XL",
        "codename": "bonito",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 670",
        "gpu": "Adreno 615",
        "ram": "4GB LPDDR4X",
        "storage": "64GB eMMC 5.1",
        "display": "6.0 inch OLED (1080x2160)",
        "battery": "3700 mAh",
        "camera": "12.2 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "flame": {
        "brand": "Google",
        "marketing_name": "Pixel 4",
        "codename": "flame",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855",
        "gpu": "Adreno 640",
        "ram": "6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "5.7 inch P-OLED 90Hz (1080x2280)",
        "battery": "2800 mAh",
        "camera": "12.2 MP + 16 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "coral": {
        "brand": "Google",
        "marketing_name": "Pixel 4 XL",
        "codename": "coral",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855",
        "gpu": "Adreno 640",
        "ram": "6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.3 inch P-OLED 90Hz (1440x3040)",
        "battery": "3700 mAh",
        "camera": "12.2 MP + 16 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "sunfish": {
        "brand": "Google",
        "marketing_name": "Pixel 4a",
        "codename": "sunfish",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 730G",
        "gpu": "Adreno 618",
        "ram": "6GB LPDDR4X",
        "storage": "128GB UFS 2.1",
        "display": "5.81 inch OLED (1080x2340)",
        "battery": "3140 mAh",
        "camera": "12.2 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "bramble": {
        "brand": "Google",
        "marketing_name": "Pixel 4a 5G",
        "codename": "bramble",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 765G 5G",
        "gpu": "Adreno 620",
        "ram": "6GB LPDDR4X",
        "storage": "128GB UFS 2.1",
        "display": "6.2 inch OLED (1080x2340)",
        "battery": "3885 mAh",
        "camera": "12.2 MP + 16 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "redfin": {
        "brand": "Google",
        "marketing_name": "Pixel 5",
        "codename": "redfin",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 765G 5G",
        "gpu": "Adreno 620",
        "ram": "8GB LPDDR4X",
        "storage": "128GB UFS 2.1",
        "display": "6.0 inch OLED 90Hz (1080x2340)",
        "battery": "4080 mAh",
        "camera": "12.2 MP + 16 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "barbet": {
        "brand": "Google",
        "marketing_name": "Pixel 5a 5G",
        "codename": "barbet",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 765G 5G",
        "gpu": "Adreno 620",
        "ram": "6GB LPDDR4X",
        "storage": "128GB UFS 2.1",
        "display": "6.34 inch OLED (1080x2400)",
        "battery": "4680 mAh",
        "camera": "12.2 MP + 16 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "orioles": {
        "brand": "Google",
        "marketing_name": "Pixel 6",
        "codename": "orioles",
        "release_year": 2021,
        "cpu_soc": "Google Tensor (1st Gen)",
        "gpu": "Mali-G78 MP20",
        "ram": "8GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.4 inch AMOLED 90Hz (1080x2400)",
        "battery": "4614 mAh",
        "camera": "50 MP + 12 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "raven": {
        "brand": "Google",
        "marketing_name": "Pixel 6 Pro",
        "codename": "raven",
        "release_year": 2021,
        "cpu_soc": "Google Tensor (1st Gen)",
        "gpu": "Mali-G78 MP20",
        "ram": "12GB LPDDR5",
        "storage": "128GB / 256GB / 512GB UFS 3.1",
        "display": "6.71 inch LTPO AMOLED 120Hz (1440x3120)",
        "battery": "5003 mAh",
        "camera": "50 MP + 48 MP + 12 MP (Rear) / 11.1 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "bluejay": {
        "brand": "Google",
        "marketing_name": "Pixel 6a",
        "codename": "bluejay",
        "release_year": 2022,
        "cpu_soc": "Google Tensor (1st Gen)",
        "gpu": "Mali-G78 MP20",
        "ram": "6GB LPDDR5",
        "storage": "128GB UFS 3.1",
        "display": "6.1 inch OLED (1080x2400)",
        "battery": "4410 mAh",
        "camera": "12.2 MP + 12 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "panther": {
        "brand": "Google",
        "marketing_name": "Pixel 7",
        "codename": "panther",
        "release_year": 2022,
        "cpu_soc": "Google Tensor G2",
        "gpu": "Mali-G710 MC10",
        "ram": "8GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.3 inch AMOLED 90Hz (1080x2400)",
        "battery": "4355 mAh",
        "camera": "50 MP + 12 MP (Rear) / 10.8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "cheetah": {
        "brand": "Google",
        "marketing_name": "Pixel 7 Pro",
        "codename": "cheetah",
        "release_year": 2022,
        "cpu_soc": "Google Tensor G2",
        "gpu": "Mali-G710 MC10",
        "ram": "12GB LPDDR5",
        "storage": "128GB / 256GB / 512GB UFS 3.1",
        "display": "6.7 inch LTPO AMOLED 120Hz (1440x3120)",
        "battery": "5000 mAh",
        "camera": "50 MP + 48 MP + 12 MP (Rear) / 10.8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "lynx": {
        "brand": "Google",
        "marketing_name": "Pixel 7a",
        "codename": "lynx",
        "release_year": 2023,
        "cpu_soc": "Google Tensor G2",
        "gpu": "Mali-G710 MC10",
        "ram": "8GB LPDDR5",
        "storage": "128GB UFS 3.1",
        "display": "6.1 inch OLED 90Hz (1080x2400)",
        "battery": "4385 mAh",
        "camera": "64 MP + 13 MP (Rear) / 13 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "shiba": {
        "brand": "Google",
        "marketing_name": "Pixel 8",
        "codename": "shiba",
        "release_year": 2023,
        "cpu_soc": "Google Tensor G3",
        "gpu": "Immortalis-G715 MC10",
        "ram": "8GB LPDDR5X",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.2 inch OLED 120Hz (1080x2400)",
        "battery": "4575 mAh",
        "camera": "50 MP + 12 MP (Rear) / 10.5 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "husky": {
        "brand": "Google",
        "marketing_name": "Pixel 8 Pro",
        "codename": "husky",
        "release_year": 2023,
        "cpu_soc": "Google Tensor G3",
        "gpu": "Immortalis-G715 MC10",
        "ram": "12GB LPDDR5X",
        "storage": "128GB / 256GB / 512GB / 1TB UFS 3.1",
        "display": "6.7 inch LTPO OLED 120Hz (1344x2992)",
        "battery": "5050 mAh",
        "camera": "50 MP + 48 MP + 48 MP (Rear) / 10.5 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },

    # --- ONEPLUS ---
    "oneplus3": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 3",
        "codename": "oneplus3",
        "release_year": 2016,
        "cpu_soc": "Qualcomm Snapdragon 820",
        "gpu": "Adreno 530",
        "ram": "6GB LPDDR4",
        "storage": "64GB UFS 2.0",
        "display": "5.5 inch Optic AMOLED (1080x1920)",
        "battery": "3000 mAh",
        "camera": "16 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "oneplus3t": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 3T",
        "codename": "oneplus3t",
        "release_year": 2016,
        "cpu_soc": "Qualcomm Snapdragon 821",
        "gpu": "Adreno 530",
        "ram": "6GB LPDDR4",
        "storage": "64GB / 128GB UFS 2.0",
        "display": "5.5 inch Optic AMOLED (1080x1920)",
        "battery": "3400 mAh",
        "camera": "16 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "cheeseburger": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 5",
        "codename": "cheeseburger",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 835",
        "gpu": "Adreno 540",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "5.5 inch Optic AMOLED (1080x1920)",
        "battery": "3300 mAh",
        "camera": "16 MP + 20 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "dumpling": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 5T",
        "codename": "dumpling",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 835",
        "gpu": "Adreno 540",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.01 inch Optic AMOLED (1080x2160)",
        "battery": "3300 mAh",
        "camera": "16 MP + 20 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "enchilada": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 6",
        "codename": "enchilada",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB / 256GB UFS 2.1",
        "display": "6.28 inch Optic AMOLED (1080x2280)",
        "battery": "3300 mAh",
        "camera": "16 MP + 20 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "fajita": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 6T",
        "codename": "fajita",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "6GB / 8GB / 10GB LPDDR4X",
        "storage": "128GB / 256GB UFS 2.1",
        "display": "6.41 inch Optic AMOLED (1080x2340)",
        "battery": "3700 mAh",
        "camera": "16 MP + 20 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "guacamoleb": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 7",
        "codename": "guacamoleb",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855",
        "gpu": "Adreno 640",
        "ram": "6GB / 8GB / 12GB LPDDR4X",
        "storage": "128GB / 256GB UFS 3.0",
        "display": "6.41 inch Optic AMOLED (1080x2340)",
        "battery": "3700 mAh",
        "camera": "48 MP + 5 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "guacamole": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 7 Pro",
        "codename": "guacamole",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855",
        "gpu": "Adreno 640",
        "ram": "6GB / 8GB / 12GB LPDDR4X",
        "storage": "128GB / 256GB UFS 3.0",
        "display": "6.67 inch Fluid AMOLED 90Hz (1440x3120)",
        "battery": "4000 mAh",
        "camera": "48 MP + 8 MP + 16 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "hotdogb": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 7T",
        "codename": "hotdogb",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855+",
        "gpu": "Adreno 640",
        "ram": "8GB LPDDR4X",
        "storage": "128GB / 256GB UFS 3.0",
        "display": "6.55 inch Fluid AMOLED 90Hz (1080x2400)",
        "battery": "3800 mAh",
        "camera": "48 MP + 12 MP + 16 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "hotdog": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 7T Pro",
        "codename": "hotdog",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855+",
        "gpu": "Adreno 640",
        "ram": "8GB / 12GB LPDDR4X",
        "storage": "256GB UFS 3.0",
        "display": "6.67 inch Fluid AMOLED 90Hz (1440x3120)",
        "battery": "4085 mAh",
        "camera": "48 MP + 8 MP + 16 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "instantnoodle": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 8",
        "codename": "instantnoodle",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 865",
        "gpu": "Adreno 650",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.0",
        "display": "6.55 inch Fluid AMOLED 90Hz (1080x2400)",
        "battery": "4300 mAh",
        "camera": "48 MP + 16 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "instantnoodlep": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 8 Pro",
        "codename": "instantnoodlep",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 865",
        "gpu": "Adreno 650",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.0",
        "display": "6.78 inch Fluid AMOLED 120Hz (1440x3168)",
        "battery": "4510 mAh",
        "camera": "48 MP + 8 MP + 48 MP + 5 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "kebab": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 8T",
        "codename": "kebab",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 865",
        "gpu": "Adreno 650",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.55 inch Fluid AMOLED 120Hz (1080x2400)",
        "battery": "4500 mAh",
        "camera": "48 MP + 16 MP + 5 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "lemonade": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 9",
        "codename": "lemonade",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 888",
        "gpu": "Adreno 660",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.55 inch Fluid AMOLED 120Hz (1080x2400)",
        "battery": "4500 mAh",
        "camera": "48 MP + 50 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "lemonadep": {
        "brand": "OnePlus",
        "marketing_name": "OnePlus 9 Pro",
        "codename": "lemonadep",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 888",
        "gpu": "Adreno 660",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.7 inch LTPO Fluid2 AMOLED 120Hz (1440x3216)",
        "battery": "4500 mAh",
        "camera": "48 MP + 8 MP + 50 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },

    # --- REALME ---
    "RMX1801": {
        "brand": "Realme",
        "marketing_name": "Realme 2 Pro",
        "codename": "RMX1801",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 660",
        "gpu": "Adreno 512",
        "ram": "4GB / 6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.3 inch IPS LCD (1080x2340)",
        "battery": "3500 mAh",
        "camera": "16 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "RMX1971": {
        "brand": "Realme",
        "marketing_name": "Realme 5 Pro",
        "codename": "RMX1971",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 712",
        "gpu": "Adreno 616",
        "ram": "4GB / 6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.3 inch IPS LCD (1080x2340)",
        "battery": "4035 mAh",
        "camera": "48 MP + 8 MP + 2 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "RMX1931": {
        "brand": "Realme",
        "marketing_name": "Realme X2 Pro",
        "codename": "RMX1931",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855+",
        "gpu": "Adreno 640",
        "ram": "6GB / 8GB / 12GB LPDDR4X",
        "storage": "64GB UFS 2.1 / 128GB / 256GB UFS 3.0",
        "display": "6.5 inch Super AMOLED 90Hz (1080x2400)",
        "battery": "4000 mAh",
        "camera": "64 MP + 13 MP + 8 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A-only (System-as-Root)",
        "supported_roms": {}
    },
    "RMX2001": {
        "brand": "Realme",
        "marketing_name": "Realme 6",
        "codename": "RMX2001",
        "release_year": 2020,
        "cpu_soc": "MediaTek Helio G90T",
        "gpu": "Mali-G76 MC4",
        "ram": "4GB / 6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.5 inch IPS LCD 90Hz (1080x2400)",
        "battery": "4300 mAh",
        "camera": "64 MP + 8 MP + 2 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "RMX2151": {
        "brand": "Realme",
        "marketing_name": "Realme 7",
        "codename": "RMX2151",
        "release_year": 2020,
        "cpu_soc": "MediaTek Helio G95",
        "gpu": "Mali-G76 MC4",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.5 inch IPS LCD 90Hz (1080x2400)",
        "battery": "5000 mAh",
        "camera": "64 MP + 8 MP + 2 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "RMX3363": {
        "brand": "Realme",
        "marketing_name": "Realme GT Master Edition",
        "codename": "RMX3363",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 778G 5G",
        "gpu": "Adreno 642L",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "128GB / 256GB UFS 2.2",
        "display": "6.43 inch Super AMOLED 120Hz (1080x2400)",
        "battery": "4300 mAh",
        "camera": "64 MP + 8 MP + 2 MP (Rear) / 32 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "RMX3370": {
        "brand": "Realme",
        "marketing_name": "Realme GT Neo 2",
        "codename": "RMX3370",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 870 5G",
        "gpu": "Adreno 650",
        "ram": "6GB / 8GB / 12GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.62 inch AMOLED 120Hz (1080x2400)",
        "battery": "5000 mAh",
        "camera": "64 MP + 8 MP + 2 MP (Rear) / 16 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },

    # --- ASUS ---
    "Z01QD": {
        "brand": "Asus",
        "marketing_name": "ROG Phone",
        "codename": "Z01QD",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "8GB LPDDR4X",
        "storage": "128GB / 512GB UFS 2.1",
        "display": "6.0 inch AMOLED 90Hz (1080x2160)",
        "battery": "4000 mAh",
        "camera": "12 MP + 8 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "I001D": {
        "brand": "Asus",
        "marketing_name": "ROG Phone II",
        "codename": "I001D",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855+",
        "gpu": "Adreno 640",
        "ram": "8GB / 12GB LPDDR4X",
        "storage": "128GB / 512GB / 1TB UFS 3.0",
        "display": "6.59 inch AMOLED 120Hz (1080x2340)",
        "battery": "6000 mAh",
        "camera": "48 MP + 13 MP (Rear) / 24 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "I003D": {
        "brand": "Asus",
        "marketing_name": "ROG Phone 3",
        "codename": "I003D",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 865+",
        "gpu": "Adreno 650",
        "ram": "8GB / 12GB / 16GB LPDDR5",
        "storage": "128GB / 256GB / 512GB UFS 3.1",
        "display": "6.59 inch AMOLED 144Hz (1080x2340)",
        "battery": "6000 mAh",
        "camera": "64 MP + 13 MP + 5 MP (Rear) / 24 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "I005D": {
        "brand": "Asus",
        "marketing_name": "ROG Phone 5",
        "codename": "I005D",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 888",
        "gpu": "Adreno 660",
        "ram": "8GB / 12GB / 16GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "6.78 inch AMOLED 144Hz (1080x2448)",
        "battery": "6000 mAh",
        "camera": "64 MP + 13 MP + 5 MP (Rear) / 24 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "I006D": {
        "brand": "Asus",
        "marketing_name": "Zenfone 8",
        "codename": "I006D",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 888",
        "gpu": "Adreno 660",
        "ram": "6GB / 8GB / 16GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "5.9 inch Super AMOLED 120Hz (1080x2400)",
        "battery": "4000 mAh",
        "camera": "64 MP + 12 MP (Rear) / 12 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "AI2202": {
        "brand": "Asus",
        "marketing_name": "Zenfone 9",
        "codename": "AI2202",
        "release_year": 2022,
        "cpu_soc": "Qualcomm Snapdragon 8+ Gen 1",
        "gpu": "Adreno 730",
        "ram": "8GB / 16GB LPDDR5",
        "storage": "128GB / 256GB UFS 3.1",
        "display": "5.9 inch Super AMOLED 120Hz (1080x2400)",
        "battery": "4300 mAh",
        "camera": "50 MP + 12 MP (Rear) / 12 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },

    # --- SONY ---
    "pioneer": {
        "brand": "Sony",
        "marketing_name": "Xperia XA2",
        "codename": "pioneer",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 630",
        "gpu": "Adreno 508",
        "ram": "3GB LPDDR4",
        "storage": "32GB eMMC 5.1",
        "display": "5.2 inch IPS LCD (1080x1920)",
        "battery": "3300 mAh",
        "camera": "23 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "voyager": {
        "brand": "Sony",
        "marketing_name": "Xperia XA2 Plus",
        "codename": "voyager",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 630",
        "gpu": "Adreno 508",
        "ram": "4GB / 6GB LPDDR4",
        "storage": "32GB / 64GB eMMC 5.1",
        "display": "6.0 inch IPS LCD (1080x2160)",
        "battery": "3580 mAh",
        "camera": "23 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "kumano": {
        "brand": "Sony",
        "marketing_name": "Xperia 1 / Xperia 5",
        "codename": "kumano",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855",
        "gpu": "Adreno 640",
        "ram": "6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.5 inch OLED 4K (1644x3840)",
        "battery": "3330 mAh",
        "camera": "12 MP + 12 MP + 12 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "pdx203": {
        "brand": "Sony",
        "marketing_name": "Xperia 1 II",
        "codename": "pdx203",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 865",
        "gpu": "Adreno 650",
        "ram": "8GB / 12GB LPDDR5",
        "storage": "256GB UFS 3.0",
        "display": "6.5 inch OLED 4K (1644x3840)",
        "battery": "4000 mAh",
        "camera": "12 MP + 12 MP + 12 MP + 0.3 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "pdx215": {
        "brand": "Sony",
        "marketing_name": "Xperia 1 III",
        "codename": "pdx215",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 888",
        "gpu": "Adreno 660",
        "ram": "12GB LPDDR5",
        "storage": "256GB / 512GB UFS 3.1",
        "display": "6.5 inch OLED 120Hz 4K (1644x3840)",
        "battery": "4500 mAh",
        "camera": "12 MP + 12 MP + 12 MP + 0.3 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },

    # --- LG ---
    "h870": {
        "brand": "LG",
        "marketing_name": "G6 (European)",
        "codename": "h870",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 821",
        "gpu": "Adreno 530",
        "ram": "4GB LPDDR4",
        "storage": "32GB / 64GB UFS 2.0",
        "display": "5.7 inch IPS LCD (1440x2880)",
        "battery": "3300 mAh",
        "camera": "13 MP + 13 MP (Rear) / 5 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "joan": {
        "brand": "LG",
        "marketing_name": "V30",
        "codename": "joan",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 835",
        "gpu": "Adreno 540",
        "ram": "4GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.0 inch P-OLED (1440x2880)",
        "battery": "3300 mAh",
        "camera": "16 MP + 13 MP (Rear) / 5 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    },
    "judyln": {
        "brand": "LG",
        "marketing_name": "G7 ThinQ",
        "codename": "judyln",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "4GB / 6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.1 inch IPS LCD (1440x3120)",
        "battery": "3000 mAh",
        "camera": "16 MP + 16 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "judypn": {
        "brand": "LG",
        "marketing_name": "V40 ThinQ",
        "codename": "judypn",
        "release_year": 2018,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "6GB LPDDR4X",
        "storage": "64GB / 128GB UFS 2.1",
        "display": "6.4 inch P-OLED (1440x3120)",
        "battery": "3300 mAh",
        "camera": "12 MP + 12 MP + 16 MP (Rear) / 8 MP + 5 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "alpha": {
        "brand": "LG",
        "marketing_name": "G8 ThinQ",
        "codename": "alpha",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855",
        "gpu": "Adreno 640",
        "ram": "6GB LPDDR4X",
        "storage": "128GB UFS 2.1",
        "display": "6.1 inch P-OLED (1440x3120)",
        "battery": "3500 mAh",
        "camera": "12 MP + 16 MP (Rear) / 8 MP + TOF 3D (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "mh2lm": {
        "brand": "LG",
        "marketing_name": "V50 ThinQ 5G",
        "codename": "mh2lm",
        "release_year": 2019,
        "cpu_soc": "Qualcomm Snapdragon 855",
        "gpu": "Adreno 640",
        "ram": "6GB LPDDR4X",
        "storage": "128GB UFS 2.1",
        "display": "6.4 inch P-OLED (1440x3120)",
        "battery": "4000 mAh",
        "camera": "12 MP + 12 MP + 16 MP (Rear) / 8 MP + 5 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },

    # --- OTHER MANUFACTURERS ---
    "fairphone4": {
        "brand": "Fairphone",
        "marketing_name": "Fairphone 4",
        "codename": "fairphone4",
        "release_year": 2021,
        "cpu_soc": "Qualcomm Snapdragon 750G 5G",
        "gpu": "Adreno 619",
        "ram": "6GB / 8GB LPDDR4X",
        "storage": "128GB / 256GB UFS 2.2",
        "display": "6.3 inch IPS LCD (1080x2340)",
        "battery": "3905 mAh",
        "camera": "48 MP + 48 MP + TOF 3D (Rear) / 25 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "fairphone5": {
        "brand": "Fairphone",
        "marketing_name": "Fairphone 5",
        "codename": "fairphone5",
        "release_year": 2023,
        "cpu_soc": "Qualcomm QCM6490",
        "gpu": "Adreno 643",
        "ram": "8GB LPDDR5",
        "storage": "256GB UFS 2.2",
        "display": "6.46 inch OLED 90Hz (1224x2700)",
        "battery": "4200 mAh",
        "camera": "50 MP + 50 MP + TOF 3D (Rear) / 50 MP (Front)",
        "partition_layout": "A/B (Virtual A/B)",
        "supported_roms": {}
    },
    "essential_mata": {
        "brand": "Essential",
        "marketing_name": "Essential Phone PH-1",
        "codename": "mata",
        "release_year": 2017,
        "cpu_soc": "Qualcomm Snapdragon 835",
        "gpu": "Adreno 540",
        "ram": "4GB LPDDR4X",
        "storage": "128GB UFS 2.1",
        "display": "5.71 inch LTPS IPS LCD (1312x2560)",
        "battery": "3040 mAh",
        "camera": "13 MP + 13 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "odin": {
        "brand": "AYN",
        "marketing_name": "Odin Handheld",
        "codename": "odin",
        "release_year": 2022,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "4GB / 8GB LPDDR4X",
        "storage": "64GB eMMC 5.1 / 128GB UFS 2.1",
        "display": "5.98 inch IPS LCD (1080x1920)",
        "battery": "6600 mAh",
        "camera": "N/A",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "shift6mq": {
        "brand": "Shiftphones",
        "marketing_name": "SHIFT6mq",
        "codename": "shift6mq",
        "release_year": 2020,
        "cpu_soc": "Qualcomm Snapdragon 845",
        "gpu": "Adreno 630",
        "ram": "8GB LPDDR4X",
        "storage": "128GB UFS 2.1",
        "display": "6.0 inch AMOLED (1080x2160)",
        "battery": "3850 mAh",
        "camera": "16 MP + 24 MP (Rear) / 13 MP (Front)",
        "partition_layout": "A/B",
        "supported_roms": {}
    },
    "axolotl": {
        "brand": "Pine64",
        "marketing_name": "PinePhone Pro",
        "codename": "axolotl",
        "release_year": 2021,
        "cpu_soc": "Rockchip RK3399S",
        "gpu": "Mali-T860 MP4",
        "ram": "4GB LPDDR4",
        "storage": "128GB eMMC 5.1",
        "display": "5.99 inch IPS LCD (720x1440)",
        "battery": "3000 mAh",
        "camera": "13 MP (Rear) / 8 MP (Front)",
        "partition_layout": "A-only",
        "supported_roms": {}
    }
}

def clear_collection(collection_ref):
    """Deletes all existing documents in the specified collection to ensure clean overwrite."""
    print("🧹 Wiping all existing documents in 'devices' collection...")
    docs = collection_ref.stream()
    deleted_count = 0
    for doc in docs:
        doc.reference.delete()
        deleted_count += 1
    print(f"🗑️ Successfully deleted {deleted_count} existing documents.\n")

def upload_catalog():
    print(f"⏳ Found {len(device_catalog)} devices in total payload. Connecting to Firestore...")

    collection_ref = db.collection("devices")

    # Clean the collection before inserting fresh dataset
    clear_collection(collection_ref)

    for codename, data in device_catalog.items():
        print(f"📦 [{codename}] Injecting {data['brand']} {data['marketing_name']}...")

        # Creates or targets the document named exactly after the phone's codename
        doc_ref = collection_ref.document(codename)

        # Sets full spec structure into Cloud Firestore
        doc_ref.set(data)

    print(f"\n✅ Finished! All {len(device_catalog)} devices were written to Firestore.")

if __name__ == "__main__":
    upload_catalog()
